apiVersion: ai.sap.com/v1alpha1
kind: Executable
metadata:
  name: azure-openai
  annotations:
    scenario.ai.sap.com/name: "foundation-models"
spec:
  image: "docker.io/sap/foundation-models:latest"
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
